apiVersion: v1
kind: Service
metadata:
  name: sqlservice
spec:
  selector:
    app: sql1
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer 

---

apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  selector:
    app: stweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  
---

apiVersion: v1
kind: Service
metadata:
  name: streactservice
spec:
  selector:
    app: streact
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
    
---

apiVersion: v1
data:
  CONN_STRING: ${SUPPORT_TICKET_DB_CONN_STRING} 
  SA_PASSWORD: ${SUPPORT_TICKET_DB_SA_PASSWORD}
kind: Secret
metadata:
  name: mssql
  namespace: default
  selfLink: /api/v1/namespaces/default/secrets/mssql
type: Opaque

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sql1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sql1
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data

--- 

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: streact-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: streact
    spec:
      containers:
      - name: streact
        image: ${SUPPORT_TICKET_REACT_IMAGE}
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: ${REACT_APP_API_URL}
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stweb
    spec:
      containers:
      - name: stweb
        image: ${SUPPORT_TICKET_WEB_API_IMAGE}
        ports:
        - containerPort: 80
        env:
        - name: CONN_STRING
          valueFrom:
            secretKeyRef:
              name: mssql
              key: CONN_STRING               
 