apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-aspnetcore-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: stweb
    spec:
      containers:
      - name: stweb
        image: stweb:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: SupportTicketSecrets