###################################################################################

# Build image - this one creates a build folder on streactbase, located at /usr/src/app/build

ARG base_image_name

FROM $base_image_name as streactbuild
RUN npm run build 

###################################################################################

# prod image - copy the build artifacts from builder

FROM streactbuild as streactprod
COPY --from=streactbuild /usr/src/app/build /usr/share/nginx/html
EXPOSE 3000


