FROM node:11.1.0 as streactbase

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
# COPY package.json /usr/src/app/package.json
COPY . /usr/src/app
RUN npm install 
RUN npm install react-scripts 

RUN npm run test:ci

CMD ["npm", "start"]
