apiVersion: v1
kind: Service
metadata:
  name: sqlservice
spec:
  selector:
    app: sql1
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer 

---

apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  selector:
    app: stweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  
  
  
