apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: streact-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: streact
    spec:
      containers:
      - name: streact
        image: ${SUPPORT_TICKET_REACT_IMAGE}
        ports:
        - containerPort: 3000