apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stweb
    spec:
      containers:
      - name: stweb
        image: ${SUPPORT_TICKET_WEB_API_IMAGE}
        ports:
        - containerPort: 80
        env:
        - name: CONN_STRING
          valueFrom:
            secretKeyRef:
              name: mssql
              key: CONN_STRING               
