version: '3'

services:
  mssql:
    #volumes:
#     - .\sqldata:/var/opt/mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlservice
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "D3vs123^^^D3vs123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
  st.web:
    environment:
      SUPPORT_TICKET_DEPLOY_DB_CONN_STRING: "Data Source=sqlservice;Initial Catalog=SupportTicket;User Id=SA;password=D3vs123^^^D3vs123"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
     - mssql
    image: virasana/stweb:1.0.0.1
    container_name: stweb
    build:
      context: .
      dockerfile: ST.Web/Dockerfile
    ports: ['80:80']
  streact:
    volumes:
     - .\streact\:/usr/src/app
    environment:
      REACT_APP_API_URL: "http://webservice/api"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
     - st.web
    image: virasana/streact:dev
    container_name: streact-dev
    build:
      context: ./streact
      dockerfile: ./Dockerfile-dev
    ports: ['3000:3000']
