version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlservice
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "D3vs123^^^D3vs123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
  st.web:
    environment:
      SUPPORT_TICKET_DEPLOY_DB_CONN_STRING: "Data Source=sqlservice;Initial Catalog=SupportTicket;User Id=SA;password=D3vs123^^^D3vs123"
      SUPPORT_TICKET_DEPLOY_JWT_SECRET: "A3D83047-A68D-4C4E-829C-181-DEV-KEY-AE9FD3CB8-375AA03A-D77F-4841-8427-69E78CB17899"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
     - mssql
    image: ${DOCKER_REGISTRY-}stweb
    container_name: stweb
    build:
      context: .
      dockerfile: ST.Web/Dockerfile
    ports: ['80:80']
  streact:
    volumes:
     - .\streact\:/usr/src/app
    environment:
      REACT_APP_API_URL: "http://webservice/api"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
     - st.web
    image: virasana/streact:dev
    container_name: streact-dev
    build:
      context: ./streact
      dockerfile: ./Dockerfile-dev
    ports: ['3000:3000']
