version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: sqlservice
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "K00s123^^^K00s123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
  st.web:
    environment:
      CONN_STRING: "Data Source=sqlservice;Initial Catalog=SupportTicket;User Id=SA;password=K00s123^^^K00s123"
    depends_on:
     - mssql
    image: virasana/stweb:1.0.0.1
    container_name: stweb
    build:
      context: .
      dockerfile: ST.Web/Dockerfile
    ports: ['80:80']
    streact:
    environment:
      WEB_API_URL: "http://some.url"
    depends_on:
     - st.web
    image: virasana/streact:dev
    container_name: streact-dev
    build:
      context: ./streact
      dockerfile: streact/Dockerfile
    ports: ['3000:3000']
